/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Dav(props) {
  const { nodes, materials } = useGLTF("/3D 4E0002.gltf");
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.04, 0.05]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_4E0002_ARD-geom"].geometry}
          material={materials._4E0002_ARD_front}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_4E0002_ARD-geom_1"].geometry}
          material={materials._4E0002_ARD_back}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_4E0002_ARD-geom_2"].geometry}
          material={materials._4E0002_ARD_edge}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/3D 4E0002.gltf");
